# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stereo_SGBM.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1247, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_pic1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pic1.setGeometry(QtCore.QRect(40, 150, 93, 28))
        self.pushButton_pic1.setObjectName("pushButton_pic1")
        self.pushButton_pic2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pic2.setGeometry(QtCore.QRect(40, 210, 101, 91))
        self.pushButton_pic2.setObjectName("pushButton_pic2")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(220, 30, 221, 151))
        self.label_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 30, 221, 151))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 200, 775, 500))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 310, 111, 81))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1247, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_pic1.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_pic2.setText(_translate("MainWindow", "SGBM视差图"))
        self.label_3.setText(_translate("MainWindow", "1、请点击SGBM视差图  2、输入左右视图"))
        self.pushButton.setText(_translate("MainWindow", "关闭界面"))
